### ISSUE TITLE
[Enhancement] Freemoji: Detect no embed perms

### ISSUE THREAD

**Issue by dav1312** [QbDesu/BetterDiscordAddons#1]
When the user doesn't have embed perms in that channel, add a brightness(.5) filter for example.

**Comment by QbDesu** [comment]
Already on my todo list. I wanted to look into it anyway because I wanted to do some tweaks like making the gif selection, hidden or at least visually look disabled when there are no embed perms. I would use the same logic for the emotes then.

**Comment by QbDesu** [comment]
Added in https://github.com/QbDesu/BetterDiscordAddons/commit/ccd7ddc7142444b2c345b82504a47473055d59b2
