### ISSUE TITLE
Please Add "Split" Feature from DiscordFreeEmojis

### ISSUE THREAD

**Issue by ImmortalZypther** [QbDesu/BetterDiscordAddons#10]
**Is your feature request related to a problem? Please describe.**

Currently, if you send an emoji using this plugin, it'll send as a massive link that'll remain next to your message.
This takes up a large amount of space (typically at the start of your message) that could be alleviated with this feature.

**Describe the solution you'd like**

In the DiscordFreeEmojis plugin from An00nymushun, there is a version of the plugin that allows you to send the emoji separately from your message to prevent it from showing as a link.
For example, if I sent "emoji.png Words words, words words", it would send as 2 messages. 1 containing the link to the image ("emoji.png"), which embedded automatically, and the message itself ("Words words, words words").
This would also work regardless of where your emoji was, front or back. It made sure to send the emoji separately from any other text to be as similar as possible to the original Nitro experience. 

**Describe alternatives you've considered**

You could always send it separately manually, but this is an extra step that the aforementioned plugin had removed. 
Transitioning from that plugin to this one is mildly more inconvenient, despite all the additional features in this one.

**Additional context**

Currently, the plugin sends like this:
![image](https://user-images.githubusercontent.com/21045587/138797569-dd2cf284-f75e-4e5a-b561-df7b599dc391.png)

I would like it to send like this:
![image](https://user-images.githubusercontent.com/21045587/138797593-7d33ec28-9de0-4580-8695-3a3b8e5c5265.png)

Or if your message is "words emoji.png", like this:
![image](https://user-images.githubusercontent.com/21045587/138797643-25f1ba66-51e9-445f-b308-c6aa8ad2b63b.png)

Although these features didn't exist in the original plugin, I propose this is how an emoji in the middle of your message would be sent ("words emoji.png words"):
![image](https://user-images.githubusercontent.com/21045587/138797790-8cfd5490-9fd9-4e8f-a3a7-d6218112ab4c.png)

And sending with an image attached would prioritize the emoji and text above the attached image because that's how it is with Nitro ("words emoji.png [attachedFile.png]").
![image](https://user-images.githubusercontent.com/21045587/138798009-4a2161c5-a6dc-4b24-9811-c7c48fc2e964.png)

**Comment by QbDesu** [comment]
Added in 1.7.0, update when prompted, won't work with attachments btw.
