### ISSUE TITLE
Send maximum size of an emoji

### ISSUE THREAD

**Issue by Halfwayclover** [QbDesu/BetterDiscordAddons#11]
Why limit it to 64px, go all the way !
plugin **DiscordFreeEmojisv1.3by An0** stopped working so here i am making the same changes to this plugin
replace get.url.replace in function getEmojiUrl with the code below to get the maximum size (original size? i have no idea) of an emoji. Works for both animated and static emojis 
            
```
                        emoji.url.replace(SIZE_REGEX,`$1v1`) :
```
Its line 358 for current version (v1.5.7)

**Comment by QbDesu** [comment]
well if you really want it you can set the size in the cofig file to something like 4096 and use that, but I won't include any sizes over 64px as a built-in options.
