### ISSUE TITLE
RemoveChatButtons no longer removes the Gift or GIF Buttons

### ISSUE THREAD

**Issue by radzo73** [QbDesu/BetterDiscordAddons#12]
**Describe the bug**
RemoveChatButtons no longer removes the Gift or GIF Buttons, even when enabled.

**To Reproduce**
1. Enable "Remove Gift Button" and/or "Remove GIF Button"
2. See that it does not remove the gift and/or gif button

**Expected behavior**
The gift and/or gif buttons are removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/26673668/139173690-0365bd5d-0b9c-43cb-91c1-332b5b60a9ff.png)

**Details (please complete the following information):**
 - Addon Name: RemoveChatButtons
 - Addon Version: 1.1.0
 - Discord Release Channel: Stable

**Additional context**
I am using CSS-Only mode, as one of my plugins (unsure which) is incompatible with it. The Sticker, Emoji, and Attach buttons are removed as intended.

**Comment by QbDesu** [comment]
Fixed in v.1.1.1, update when prompted. Thanks for reporting it!
