### ISSUE TITLE
Settings toggles not working

### ISSUE THREAD

**Issue by Achenar459** [QbDesu/BetterDiscordAddons#15]
**Describe the bug**
It appears as if the REMOVE GRAYSCALE FILTER, MISSING EMBED PERMS BEHAVIOR, ALLOW UNAVAILABLE EMOJI, and ALLOW EXTERNAL EMOJI should be able to be toggled on/off in Settings, however they are just listed with descriptions, but the toggle button is not there.

**To Reproduce**
1. Go to 'FREEMOJI SETTINGS'
Only the toggle for "Send Directly" is there

**Expected behavior**
The ability to toggle on/off the settings such as REMOVE GRAYSCALE FILTER

**Screenshots**
![image](https://user-images.githubusercontent.com/11438347/141345035-06069eab-0e68-404d-b9af-aeef68b80a1f.png)

**Details (please complete the following information):**
 - Addon Name: Freemoji
 - Addon Version: v1.5.7 by Qb, An0
 - Discord Release Channel: Stable/PTB

**Additional context**
Not having a grayscale filter makes it impossible to know which emojis you can use as reactions to messages.

**Comment by MarrcosabTTS** [comment]
Still not fixed :/

**Comment by doggybootsy** [comment]
this is a bug with ZerespluginLibrary not this plugin

**Comment by QbDesu** [comment]
https://github.com/rauenzi/BDPluginLibrary/pull/106
