### ISSUE TITLE
Plugin not working.

### ISSUE THREAD

**Issue by abinroy04** [QbDesu/BetterDiscordAddons#16]
For unknown reasons, the plugin does not work for me.
![image](https://user-images.githubusercontent.com/85763004/143176647-16690a0d-357a-48da-bb08-01a9a39e325f.png)
Comes like this in chat.

I think the link is not being generated.

 - Addon Name: Freemoji
 - Addon Version: 1.5.7
 - Discord Release Channel: Stable

**Comment by QbDesu** [comment]
Try the 1.6.0 update I just pushed. Make sure the plugin is enabled and you don't have plugins like NitroPerks which may conflict with it.
