### ISSUE TITLE
emojies dont show in the list

### ISSUE THREAD

**Issue by Idelives** [QbDesu/BetterDiscordAddons#18]
**Describe the bug**
When typing the name of a emoji it does not show in the "Emoji matching" list

**To Reproduce**
typing the emoji name doesnt show the expected results only showing the normal results

**Expected behavior**
In normal circumstances it would be expected to see a list of emojies that includes all matching with the :emoji_name: regardless of the server

**Screenshots**
Current Result:
[https://cdn.discordapp.com/attachments/334930809289179137/910028629994508328/unknown.png](url)

Expected Result:
[https://cdn.discordapp.com/attachments/334930809289179137/910028689083875358/unknown.png](url)

**Details (please complete the following information):**
 - Addon: Freemoji
 - Addon Version: Freemoji v1.5.7by Qb, An0
 - Discord Release Channel: public release available in BD server 2

**Additional context**
problem occurs in groups, dms and servers with no exception

**Comment by QbDesu** [comment]
Just pushed an update (1.6.0) that should fix the issue. If you still run into trouble after updating to 1.6.0 be sure to let me know.
