### ISSUE TITLE
plugin completley broken 

### ISSUE THREAD

**Issue by itsben69** [QbDesu/BetterDiscordAddons#19]
every message you send excluding images is being sent twice at once for some reason.

**Comment by QbDesu** [comment]
did you try reloading your client? and there is an issue template for a reason

**Comment by itsben69** [comment]
sorry i don’t use github all that much and don’t really know how shit works but yeah i’ve reloaded it with ctrl r and also completely ended task and restarted it and same problem occurs every time i turn the  plug in on

**Comment by QbDesu** [comment]
addon name, addon version, discord release channel (stable/ptb/canary), betterdiscord version...

**Comment by itsben69** [comment]
discord stable 
BetterDiscord 1.3.0
plugin: Freemojiv1.7.0
issue: Sending messages with the plugin on causes messages to be duplicated and sent twice, started happening just now when i clicked on a banner saying i need to update this plugin.

sorry for the shit report earlier haha

**Comment by QbDesu** [comment]
what are your settings for freemoji? do you have any similar plugins installed like nitro perks for example. Does it also happen when you turn of Splitting?

**Comment by itsben69** [comment]
now that I checked i also had emote replacer on and i turned it off and the problem solved 😅, but besides that i had default settings and what not but ig  that solves it, sorry for wasting your time
