### ISSUE TITLE
BetterBotTags: Replying to Webhook Messages shows a regular "BOT" Tag

### ISSUE THREAD

**Issue by NathanLithia** [QbDesu/BetterDiscordAddons#21]
**Describe the bug**
When a bot replies to a webhook that webhook on the reply is shown as a bot rather than a webhook like the original webhook

**To Reproduce**
Get a bot to reply to a webhook

**Expected behavior**
I expected the reply to have a webhook tag rather than a bot tag

**Screenshots**
[https://cdn.discordapp.com/attachments/743644002955558985/915845679052623882/unknown.png](https://cdn.discordapp.com/attachments/743644002955558985/915845679052623882/unknown.png)

**Details (please complete the following information):**
 - Addon Name: [BetterBotTags]
 - Addon Version: [v1.0.1]
 - Discord Release Channel: [Stable]

**Additional context**
I'll upload a picture incase the link is invalid
![Discord_0Xwp5xhbF5](https://user-images.githubusercontent.com/10991641/144367019-7951713a-fbd4-4737-8cf5-5a2154d8f549.png)

**Comment by rollingmoai** [comment]
@QbDesu latest version no longer has this bug. Can you close this?
