### ISSUE TITLE
Freemoji  add direct upload option

### ISSUE THREAD

**Issue by jfish871** [QbDesu/BetterDiscordAddons#23]
**Is your feature request related to a problem? Please describe.**
For the Freemoji plugin maybe add an option to have the plugin download the file directly and post it as an image instead of relying on posting a link to the image. If the user dose not have embed perms then they can't post the image directly.

**Describe the solution you'd like**
I think it would be a good idea to add the option to allow a user to toggle between sending a link to the file in the CDN and downloading the file and uploading it directly.

**Comment by QbDesu** [comment]
Plugin was discontinued.
