### ISSUE TITLE
Some settings appear as unclickable invisible boxes

### ISSUE THREAD

**Issue by AshPikachu1** [QbDesu/BetterDiscordAddons#24]
**Describe the bug**
Some settings appear as unclickable invisible boxes (when hovered it darkens)

**To Reproduce**
It just does i'm guessing an update broke it

**Expected behavior**
Perhaps a dropdown menu of some sort

**Screenshots**
![image](https://user-images.githubusercontent.com/78652092/146483977-ef44d08a-44b7-42f9-9b8d-95e1df821bcd.png)

**Details (please complete the following information):**
 - Addon Name: [e.g. Freemoji]]
 - Addon Version: [e.g. 1.0.0]
 - Discord Release Channel: [Stable/PTB/Canary]

**Additional context**
None

**Comment by QbDesu** [comment]
see #15
