### ISSUE TITLE
Emote selection in reaction tab

### ISSUE THREAD

**Issue by cbrt-x** [QbDesu/BetterDiscordAddons#25]
**Describe the bug**
When selecting an emote to react with it shows normally nitro-only emotes that will not work when clicked on
-> use the normal menu here?

**To Reproduce**
1. Go to a message
2. Click on react
3. choose a nitro-only emote

**Expected behavior**
Normal menu should pop up

**Details (please complete the following information):**
 - Addon Name: Freemoji
 - Addon Version: e.g. 1.7.0
 - Discord Release Channel: Stable

**Comment by QbDesu** [comment]
This was known, the method used to patch it couldn't differentiate between the reaction emoji picker and the regular chat emojis. The plugin is now discontinued anyway.
