### ISSUE TITLE
Plugin straight up wont work for me; help

### ISSUE THREAD

**Issue by bl4st-github** [QbDesu/BetterDiscordAddons#29]
Plugin installed, neither Freemoji or FreeEmojis work, attempted with both emoji picker and text.
![2](https://user-images.githubusercontent.com/82440988/149922418-c3d8fe30-8288-49ae-b66c-d89e54ae1098.png)
![3](https://user-images.githubusercontent.com/82440988/149922423-1af9da59-5831-4bef-9dbc-2a7abc99305c.png)
![1](https://user-images.githubusercontent.com/82440988/149922426-6575e9d6-d66f-475f-9c6a-5024a3177d4a.png)

**Comment by TheVirus-Limiter** [comment]
same

**Comment by Ishj21** [comment]
any updates?
Edit: Disabling ZeresPluginLibrary works for me, also disable any other emote plugins and try again.
