### ISSUE TITLE
Add a setting to disable the automatic text to emoji

### ISSUE THREAD

**Issue by Rixarlin** [QbDesu/BetterDiscordAddons#31]
**Is your feature request related to a problem? Please describe.**
When I type "Noice" or "Moonshine" it automatically converts it to an emoji that I don't want. If I wanted to use an emoji I would have used one.

**Describe the solution you'd like**
Add a setting to allow people to disable this automatic text to emoji conversion.

**Describe alternatives you've considered**
Just remove it entirely :)

**Comment by QbDesu** [comment]
That's a BetterDiscord feature and is part of BetterDiscord's Twitch Emote System, it's not related to this plugin.
