### ISSUE TITLE
messages send twice

### ISSUE THREAD

**Issue by 0kom** [QbDesu/BetterDiscordAddons#32]
**Describe the bug**
all messages send twice when the plugin is on
**To Reproduce**
1. literaly send a message with the plugin on
2. See 2 of that message

**Details (please complete the following information):**
 - Addon Name: Freemoji
 - Addon Version: 1.7.0
 - Discord Release Channel: [Stable]

**Comment by QbDesu** [comment]
This is most commonly caused by an interaction with the EmoteReplacer plugin. An update working around the issue has been pushed and it should fix the issue if it was actually caused by EmoteReplacer. If that didn't fix it be sure to comment on this issue again or open a new one.
