### ISSUE TITLE
screenshare spoof fix? idk

### ISSUE THREAD

**Issue by ZellsAlpha** [QbDesu/BetterDiscordAddons#35]
Possibly fix  Freemoji not sending when using

BdApi.findModuleByProps("getCurrentUser").getCurrentUser().premiumType = 2;

for nitro screenshare?

**Comment by SpookieGames** [comment]
Yeah would be wonderful

**Comment by QbDesu** [comment]
No, I won't add that to freemoji, and it wouldn't be allowed in official plugins anyway.
