### ISSUE TITLE
Freemoji plugin seems to be broken

### ISSUE THREAD

**Issue by SpookieGames** [QbDesu/BetterDiscordAddons#37]
When I type :emote: it just sends the message without any image

**Comment by BigFlubba** [comment]
Cannot reproduce. Is the plugin updated and is it enabled.

**Comment by SpookieGames** [comment]
Yeah. Will send you video

**Comment by SpookieGames** [comment]
https://user-images.githubusercontent.com/41782443/150691550-4c357f71-80b6-4277-8ead-15b200eb02d5.mp4

**Comment by SpookieGames** [comment]
Okay I removed every plugin and theme and it seems it works now. There must be something interfering. Thanks
