### ISSUE TITLE
Feature request for RemoveChatButtons - Being able to hide the Nitro channel

### ISSUE THREAD

**Issue by Obazzi** [QbDesu/BetterDiscordAddons#39]
**Is your feature request related to a problem? Please describe.**
The Nitro channel that is situated underneath the Friends button is useless, an eye soar and basically an ad. Also, I used to get rid of it with custom CSS, but it always breaks, and I have no idea how to fix it, so I have to go asking around in the BetterDiscord Discord server.

**Describe the solution you'd like**
Being able to disable the Nitro channel by enabling the "Disable Nitro channel" in the settings of the "RemoveChatButtons" plugin. I know it is not a chat button, but it is an annoyance just like the chat button, and it is the same intention (removing it). Maybe you would need to change the plugin name to RemoveAnnoyances? (not necessary imo).

**Describe alternatives you've considered**
Using custom CSS, but it always breaks. It also didn't work with the pin dms plugin, but I don't use it anymore so idk if it is still an issue.

**Additional context**
How it currently is:
![image](https://user-images.githubusercontent.com/88412380/152202608-0e310094-85e1-4b2d-8bf7-b3b09ab21d5c.png)
And after enabling this feature in the plugin's settings:
![image](https://user-images.githubusercontent.com/88412380/152202929-0ac766dd-bc81-4010-8087-b41de823c56f.png)
(this image was edited in paint.net because, as I said earlier, my custom CSS broke, so it probably looks more scuffed then it will actually look)

**Comment by QbDesu** [comment]
Added in 1.2.1, update when prompted to
