### ISSUE TITLE
BetterBotTags - Discord Client Crash (Stable 115008 (97968e1))

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [QbDesu/BetterDiscordAddons#40]
**Describe the bug**
Discord client crashes with BetterBotTags Enabled

**To Reproduce**
1. Enable BetterBotTags
2. go to a server with lots bots in the one channel with embeds etc..
3. refresh discord & it should crash when trying to load the embeds posted by bots

**Expected behavior**
for it not to kill my discord client?

**Screenshots**
![Screen Shot 2022-02-16 at 5 32 13 pm](https://user-images.githubusercontent.com/2242880/154220647-72527616-c856-457c-8da3-9cdef8f40021.jpg)

**Details (please complete the following information):**
 - Addon Name: BetterBotTags
 - Addon Version: 1.0.0
 - Discord Release Channel: Stable

**Additional context**
[Video Demo](https://www.dropbox.com/s/uk7z4yyl7a6hbov) Of Crash
[debug.log](https://github.com/QbDesu/BetterDiscordAddons/files/8077885/debug.log)

**Comment by just5ky** [comment]
+1 on this
Took me 1hour to go through all my plugins to find out it was this.

**Comment by QbDesu** [comment]
Just pushed a quick temporary fix for BetterBotTags, you should be prompted to update soon-ish. It other crashes occur be sure to let me know.
