### ISSUE TITLE
[BUG] RemoveChatButtons - Not working on ptb and canary

### ISSUE THREAD

**Issue by wilecoyote** [QbDesu/BetterDiscordAddons#42]
**Describe the bug**
Plugin is broken on ptb and canary

**To Reproduce**
Activate the plugin on ptb and canary and rry to deactivate gift, gif or sticker button

**Expected behavior**
Buttons should be hidden

**Screenshots**

**Details (please complete the following information):**
 - Addon Name: RemoveChatButtons 
 - Addon Version: 1.1.2
 - Discord Release Channel: PTB, Canary

**Additional context**
Happened after current updates on these release channels

**Comment by QbDesu** [comment]
Cannot reproduce this. Just tested it on Canary using both with the CSS-only mode and without it and it worked fine. Maybe it's a change they have undone by now but this seems to no longer be valid.
