### ISSUE TITLE
FreeMoji breaks replying

### ISSUE THREAD

**Issue by SeasonalFerret** [QbDesu/BetterDiscordAddons#46]
**Describe the bug**
When you reply to a message, inserting a freemoji sends the first message without replying

**To Reproduce**
1. Rightclick someone else's message, hit Reply
2. Type a message with a nitro emoji, send it
3. Notice that both your message and the emoji get sent, however your message is not a reply

**Expected behavior**
The first message sent should be replying to the message you clicked Reply on.
To prevent spam, the second message / emoji should not be a reply.

**Screenshots**
"Test Message 2" is a reply to "Test Message 1", as intended.
"Test Response" fails the reply.
https://user-images.githubusercontent.com/17802843/161789492-44dc77e0-b043-417b-8ff4-f1091659dad2.mp4

**Details (please complete the following information):**
 - Addon Name: Freemoji
 - Addon Version: v1.7.1
 - Discord Release Channel: Stable

**Comment by JohnnyToumieh** [comment]
EDIT: This actually introduces an error in the console about missing author or something i believe

I added this line of code and made it work on my end. effectively you are preserving the first part of the message properties and then sending separate messages for the rest of the splits.

```
if (i == 0) {
  var firstMessage = message;
  firstMessage.content = text;
  args.message = firstMessage;
  originalFn.apply(thisObj, args);
  continue;
}
```

Until the coder fixes it on their end, you can add this in the for loop below:
**BEFORE**
```
                            for (let i = 0; i < split.length; i++) {
                                const text = split[i];

                                promises.push(new Promise((resolve, reject) => {
                                    window.setTimeout(() => {
                                        originalFn.call(thisObj, channel, { content: text, validNonShortcutEmojis: [] }).then(resolve).catch(reject);
                                    }, i * 100);
                                }));
                            }
```

**AFTER**
```
                            for (let i = 0; i < split.length; i++) {
                                const text = split[i];

                                if (i == 0) {
                                    var firstMessage = message;
                                    firstMessage.content = text;
                                    args.message = firstMessage;
                                    originalFn.apply(thisObj, args);
                                    continue;
                                }

                                promises.push(new Promise((resolve, reject) => {
                                    window.setTimeout(() => {
                                        originalFn.call(thisObj, channel, { content: text, validNonShortcutEmojis: [] }).then(resolve).catch(reject);
                                    }, i * 100);
                                }));
                            }
```
