### ISSUE TITLE
DoubleClickVoiceChannels -Console Log

### ISSUE THREAD

**Issue by nirgranth** [QbDesu/BetterDiscordAddons#48]
**Screenshots**
![image](https://user-images.githubusercontent.com/48947296/163449517-f29e03ef-50f9-4a80-996a-3fe14f9347c7.png)

**Details (please complete the following information):**
Stable 123887 (00d8cb1)
BetterDiscord 1.5.3
Host 1.0.9004 Windows 10 64-Bit (10.0.19044)

**Comment by QbDesu** [comment]
The plugin was finally fixed after being broken for quite a long time. The way it patches the channel list was reworked and is a lot more reliable now and should no longer spam the console.
