### ISSUE TITLE
A new button for RemoveChatButtons to remove

### ISSUE THREAD

**Issue by radzo73** [QbDesu/BetterDiscordAddons#49]
![image](https://user-images.githubusercontent.com/26673668/164105711-be78c77c-1058-4475-ab9a-f55cc909b091.png)

**Is your feature request related to a problem? Please describe.**
Discord has recently introduced a new button to the message inbarput, the Boost button. Unlike any other button in the message bar, I cannot hide it with RemoveChatButtons.

**Describe the solution you'd like**
Allow the hiding of this new Boost button, like any other button in the message bar.

**Describe alternatives you've considered**
Any other solution would be kinda weird, considering that hiding buttons in the message bar is kinda the thing this plugin _does_,

**Additional context**
N/A

**Comment by QbDesu** [comment]
Oh no, not yet another annoying button. Thanks for reporting it, I haven't encountered it yet but I will make sure to release an update for RemoveChatButtons as soon as I do

**Comment by QbDesu** [comment]
Was already working out of the box as long as CSS-only mode was turned off. Updating to version 1.2.2 makes it work in CSS-only mode as well.
