### ISSUE TITLE
Freemoji | Other Server's Emoji Warning for Non-Nitro Users

### ISSUE THREAD

**Issue by Malix-Labs** [QbDesu/BetterDiscordAddons#50]
# Other Server's Emoji Warning for Non-Nitro Users

_It also applies to DMs_

## Exemple
![image](https://user-images.githubusercontent.com/76160668/166123993-484af63a-048c-40c4-8113-abcc445c6c64.png)
>> ![image](https://cdn.discordapp.com/emojis/935655955650195557.webp?size=44&quality=lossless)
> 
>> This emoji doesn't work here because it's from a different server. Upgrade to Discord Nitro to use emoji from other servers

**Comment by QbDesu** [comment]
Fixed in 1.7.3, update when prompted to
