### ISSUE TITLE
What are the potential values/constants in EmojiDisabledReasons?

### ISSUE THREAD

**Issue by JohnnyToumieh** [QbDesu/BetterDiscordAddons#52]
`DiscordConstants: {
                            EmojiDisabledReasons,
                            EmojiIntention
                        }`

Sorry for being unprofessional and opening a ticket here, I just had no idea how to reach you and I haven't found anything online on this.
My goal is to check if an emoji is from the current server where it's being used in and this is the best method i thought might work compared to getting all emojis from a specific server and then looking up the emote inside that list.
If there is something like EmojiDisabledReasons.ANIMATEDEMOTE (to indicate it's not from an outside server, it's just disabled because the emote is animated and the user doesn't have nitro, then i would like to check this)

**Comment by QbDesu** [comment]
```json
{
    "0": "DISALLOW_EXTERNAL",
    "1": "GUILD_SUBSCRIPTION_UNAVAILABLE",
    "2": "PREMIUM_LOCKED",
    "3": "ONLY_GUILD_EMOJIS_ALLOWED",
    "DISALLOW_EXTERNAL": 0,
    "GUILD_SUBSCRIPTION_UNAVAILABLE": 1,
    "PREMIUM_LOCKED": 2,
    "ONLY_GUILD_EMOJIS_ALLOWED": 3
}
```
Animated emoji fall under `PREMIUM_LOCKED`

The emoji object itself does however contain infos such as the guildid and whether the emoji is animated.
```json
{
    "animated": false,
    "available": true,
    "id": "422040824201609226",
    "managed": false,
    "name": "intrnlmini",
    "require_colons": true,
    "roles": [],
    "url": "https://cdn.discordapp.com/emojis/422040824201609226.webp?size=48&quality=lossless",
    "allNamesString": ":intrnlmini:",
    "guildId": "86004744966914048"
}
```
