### ISSUE TITLE
Emote menu searchbar not cleared after reacting to a server message

### ISSUE THREAD

**Issue by JohnnyToumieh** [QbDesu/BetterDiscordAddons#53]
**Describe the bug**
When you react to a server message with an emote (having used the search functionality by typing), the next instance of accessing the emote menu, you will find that the search was not cleared.

**To Reproduce**
1. Click "Add Reaction" to a message INSIDE A SERVER (not DMs)
2. Type a normally usable emote name in the search bar and select the emote
3. Access the emote menu again and you will find the last search is still there (not cleared)

**Expected behavior**
In step 3, we should see the search field empty and the emotes not filtered

**Details (please complete the following information):**
 - Addon Name: Freemoji
 - Addon Version: 1.7.3
 - Discord Release Channel: Stable

**Comment by QbDesu** [comment]
Closing this because Freemoji was discontinued a couple months ago. Be sure to check out EmoteReplacer instead.
