### ISSUE TITLE
[Freemoji] - Not working as intended

### ISSUE THREAD

**Issue by BigFlubba** [QbDesu/BetterDiscordAddons#55]
**Describe the bug**
Cannot use Freemoji as intended in the emoji picker.

**To Reproduce**
1. Open emoji picker
2. Click on any server emoji

**Expected behavior**
Emoji sends as an image.

**Recording**
https://user-images.githubusercontent.com/69104450/172978831-68cf3ab8-d531-40c3-a8d4-39178e7b839a.mp4

**Details (please complete the following information):**
 - Addon Name: Freemoji
 - Addon Version: 1.7.3
 - Discord Release Channel: Stable

**Additional context**
Has been broken for a long time now.

**Comment by QbDesu** [comment]
Plugin discontinued.
