### ISSUE TITLE
Freeemoji: Send images as PNG instead of WebP 

### ISSUE THREAD

**Issue by Katzenwerfer** [QbDesu/BetterDiscordAddons#59]
In discord, WebP images have a lower quality preview than PNGs, even when the `&lossless` parameter is specified in the URL.

Having an option, or moving entirely, to using the PNG extension for the URLs would be a nice change to have for the quality of the images.

![image](https://user-images.githubusercontent.com/53267697/176053759-4d439860-098f-4187-a37a-91efe5b8a023.png)
[WebP](https://cdn.discordapp.com/emojis/852393444839522325.webp?size=48) | [PNG](https://cdn.discordapp.com/emojis/852393444839522325.png?size=48)

**Comment by QbDesu** [comment]
well technically it's not yet completed as the version wasn't bumped yet so there was never really an update, you could only get it if you build it from source. but yeah I will do some changes and will bump the version and do some changes some time this week.
