### ISSUE TITLE
[BUG] Remove Startup Toasts - Error: Meta was not found

### ISSUE THREAD

**Issue by zluckytraveler** [QbDesu/BetterDiscordAddons#63]
**Describe the bug**
Error Message: Meta was not found

**To Reproduce**
Dropping the file into the plugins directory

**Expected behavior**
Not to receive an error.

**Screenshots**
<img width="659" alt="Screen Shot 2022-08-14 at 4 30 47 PM" src="https://user-images.githubusercontent.com/97180817/184558984-4d7ec8f1-c62c-461a-a04b-6763704fc4c2.png">

**Details (please complete the following information):**
 - Addon Name: ZZRemoveStartupToasts.plugin.js
 - Addon Version: N/A
 - Discord Release Channel: Stable

**Additional context**
N/A

**Comment by QbDesu** [comment]
Can't reproduce, sounds like the file you are trying to load is something other than a plugin, perhaps you did right-click -> save as... on an html page instead of a raw plugin file.
