### ISSUE TITLE
Not an issue, but a thanks

### ISSUE THREAD

**Issue by hydino2085143** [QbDesu/BetterDiscordAddons#67]
Thank you for being magnanimous about the deprecation of this plugin.

**Comment by SollyBunny** [comment]
Although I'm against the removal/deprecation of these plugins I want to give thanks to those who gave their time for free to develop and maintain them: Thanks! :)

**Comment by amoruwu** [comment]
lmao the people who were upset about show ////// channels and saying it's not different then emoji plug in are going to get so buthurt about this news. I understand how hard the maintenance of a plug-
in can be, and I would like to thank the people who can do it. much love to all of them <3

**Comment by Khosraw** [comment]
I can't believe some people thought it was the end of the world. It was enough for them to spread hate like crazy...

Thank you for the maintenance of the plugin :)

**Comment by Nos74** [comment]
Nicely written excuse to stop maintaining this plugin.

**Comment by Weblure** [comment]
If you were just discontinuing maintaining the plugin because you didn't have the time or drive anymore, people would be fine with that. It's the fact that a perfectly-functioning plugin was forcibly disabled without any user's consent. You have the gall to call your work unlicensed, and then turn around and claim that you and BD have the right to destroy users' property without warning?

People aren't mad at you for discontinuing a plugin. They're mad at you for unconsentually disabling content on their computer and then acting like a complete shill about it and painting them as bad people — because god forbid they want to make sure there's no shady groomer shit going on behind the curtains in a server they joined. Blame Discord's dogshit security, not the people taking advantage of it for harmless reasons.

I appreciate your hard work, but I don't appreciate the game you're trying to play. If you don't want to continue working on something, just say that and be done with it. You don't need an excuse or reason. Plenty of people will be happy to pick up where you left off — if they weren't being prevented from doing so, that is. You don't need to play it up like you're taking some grand moral stand and then seek pity because some random idiots started saying mean things to you.

Yeah dude, welcome to the internet. I wish you luck going forward.

**Comment by Derpitron** [comment]
> Nicely written excuse to stop maintaining this plugin.

That's his choice to make in the end.

**Comment by Derpitron** [comment]
> If you were just discontinuing maintaining the plugin because you didn't have the time or drive anymore, people would be fine with that. It's the fact that a perfectly-functioning plugin was forcibly disabled without any user's consent. You have the gall to call your work unlicensed, and then turn around and claim that you and BD have the right to destroy users' property without warning?
> 
> People aren't mad at you for discontinuing a plugin. They're mad at you for unconsentually disabling content on their computer and then acting like a complete shill about it and painting them as bad people — because god forbid they want to make sure there's no shady groomer shit going on behind the curtains in a server they joined.

Freemoji was the only discontinued plugin. And how does an emoji plugin increase transparency in a server? Besides, Freemoji had an update consent modal dialog which allowed you to keep the plugin fully functioning, no strings attached.

Sounds like you just copy-pasted this rant from some cringey "anti censorship" reddit comment without even bothering to understand what's going on regarding the Freemoji plugin itself.

**Comment by TaklaPro** [comment]
Man kudos to the creator! Thanks for developing such a useful plugin!! I would love to see this project being revived again!!

**Comment by Weblure** [comment]
> > If you were just discontinuing maintaining the plugin because you didn't have the time or drive anymore, people would be fine with that. It's the fact that a perfectly-functioning plugin was forcibly disabled without any user's consent. You have the gall to call your work unlicensed, and then turn around and claim that you and BD have the right to destroy users' property without warning?
> > People aren't mad at you for discontinuing a plugin. They're mad at you for unconsentually disabling content on their computer and then acting like a complete shill about it and painting them as bad people — because god forbid they want to make sure there's no shady groomer shit going on behind the curtains in a server they joined.
> 
> Freemoji was the only discontinued plugin. And how does an emoji plugin increase transparency in a server? Besides, Freemoji had an update consent modal dialog which allowed you to keep the plugin fully functioning, no strings attached.
> 
> Sounds like you just copy-pasted this rant from some cringey "anti censorship" reddit comment without even bothering to understand what's going on regarding the Freemoji plugin itself.

Sorry, but after reading [this rant](https://github.com/QbDesu/BetterDiscordAddons/blob/potato/Plugins/Freemoji/DISCONTINUATION.md) about how "the community was obnoxious" about ShowHiddenChannels being forcibly disabled on people's computers, I was under the assumption that QbDesu was the developer of that plugin. The fact that they aren't just makes this even more retarded.

 So, what? They saw a few people being understandably upset at a dev for doing something scummy and then decided to punish the entire community by dropping support for a random plugin of theirs, when neither they nor their plugin had any involvement whatsoever? That's the saddest shit I've ever heard lmfao. They're literally just scrounging for attention off of a controversy that had absolutely nothing to do with them.

**Comment by RossoFiamma99** [comment]
> 

Seems just like anyone working on this plugin was an ass. 
Literally, they just decided to punish the whole community just to prove something to a small selection of people. I didn't know jackshit about all the drama that was going on, and yet, here we are.

**Comment by anxietyprimev69** [comment]
Kinda sucks that this plugin was axed because of some braindead reddit drama I don't care about, but I'd be lying if I said I didn't appreciate it while it was here. So thanks for that. I hope you change your mind, but if not at least this gives me an excuse to learn Javascript.

Pro tip, you can always just steal other people's emotes and use them whenever by saving them as PNGs. Or just downscale your own images and use them as pseudo-emotes. It's bummy, but it works and it's completely free.

**Comment by Derpitron** [comment]
> > 
> 
> Seems just like anyone working on this plugin was an ass. Literally, they just decided to punish the whole community just to prove something to a small selection of people. I didn't know jackshit about all the drama that was going on, and yet, here we are.

You are not owed this plugin at all.

**Comment by RossoFiamma99** [comment]
> > > 
> > 
> > 
> > Seems just like anyone working on this plugin was an ass. Literally, they just decided to punish the whole community just to prove something to a small selection of people. I didn't know jackshit about all the drama that was going on, and yet, here we are.
> 
> You are not owed this plugin at all.

So yeah, let's just stop supporting this plugin due to pettiness
Fuck the rest of the community who done nothing, loved this plugin and used it daily. Am I rite?

**Comment by Derpitron** [comment]
> > > > 
> > > 
> > > 
> > > Seems just like anyone working on this plugin was an ass. Literally, they just decided to punish the whole community just to prove something to a small selection of people. I didn't know jackshit about all the drama that was going on, and yet, here we are.
> > 
> > 
> > You are not owed this plugin at all.
> 
> So yeah, let's just stop supporting this plugin due to pettiness Fuck the rest of the community who done nothing, loved this plugin and used it daily. Am I rite?

Yes. If you really care so much about it why not fork it and maintain that yourself? or does your "love of this plugin" extend only so far as to beg for updates and support and whine like a toddler when you don't get what you want?

**Comment by RossoFiamma99** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Seems just like anyone working on this plugin was an ass. Literally, they just decided to punish the whole community just to prove something to a small selection of people. I didn't know jackshit about all the drama that was going on, and yet, here we are.
> > > 
> > > 
> > > You are not owed this plugin at all.
> > 
> > 
> > So yeah, let's just stop supporting this plugin due to pettiness Fuck the rest of the community who done nothing, loved this plugin and used it daily. Am I rite?
> 
> Yes. If you really care so much about it why not fork it and maintain that yourself? or does your "love of this plugin" extend only so far as to beg for updates and support and whine like a toddler when you don't get what you want?

Yeah, sure, hold on while I learn how to script it and maintain it.
Dude, pull your head out of your ass. If I were able to, you can bet I would've already done so. It's a labor of love for the whole community. Everyone benefits from it. But you seem too much stuck up to understand this. Egoistic prick

**Comment by Derpitron** [comment]
Perhaps you missed this clause in the license? 

https://github.com/QbDesu/BetterDiscordAddons/blob/ce44bd09f9ea0c9a668d33e4e91239e02dd48c79/LICENSE#L16-L22

> Yeah, sure, hold on while I learn how to script it and maintain it.
Dude, pull your head out of your ass. If I were able to, you can bet I would've already done so. It's a labor of love for the whole community. Everyone benefits from it. But you seem too much stuck up to understand this. Egoistic prick

You don't even know how to maintain this plugin yet you're whining at other people for your own technical incompetency, demanding they fix things they've made just to make you happy? You're the "egoistic prick", trying to guilt trip and force a developer into following your will. Unlicense is equivalent to public domain in most jurisdictions, and there are free tutorials for learning Javascript online. The rest is up to you. Godspeed, soldier

**Comment by RossoFiamma99** [comment]
> Perhaps you missed this clause in the license?
> 
> https://github.com/QbDesu/BetterDiscordAddons/blob/ce44bd09f9ea0c9a668d33e4e91239e02dd48c79/LICENSE#L16-L22

1) No, I did not read it. 2) I'm here just to express my disappointment. I couldn't care less about github. While I do appreciate people supporting/creating this kind of stuff (Or any kind of thing I've found through the years by using Github, really saved my life a lot of times), I have no experience in script/coding. 3) It's petty. I won't change my mind over this. I did my part in modding/sound/music for other games, it takes nothing to add to the world. You can keep on showing me the license all you want, but it still won't change the fact that the depreciation of this plugin affects people. People who maybe cannot afford Nitro for a reason or another.

**Comment by Derpitron** [comment]
It took me less than 5 seconds to find [this actively maintained Nitro bypass plugin](https://github.com/riolubruh/YABDP4Nitro) on Github. All the best for your future world changing endeavours of sending animated emojis and 240 fps screensharing 😉

**Comment by RossoFiamma99** [comment]
> It took me less than 5 seconds to find [this actively maintained Nitro bypass plugin](https://github.com/riolubruh/YABDP4Nitro) on Github. All the best for your future world changing endeavours of sending animated emojis and 240 fps screensharing 😉

My "world changing endeavours" have nothing to do with Discord.
Mine is a matter of "helping the community". I could've gone over this about anything else.
But I appreciate the plugin link.

**Comment by SeasonalFerret** [comment]
fuck it I'm just buying nitro
