### ISSUE TITLE
PanelPopout not working

### ISSUE THREAD

**Issue by plasmaborg** [QbDesu/BetterDiscordAddons#7]
**Describe the bug**
PanelPopout does not work and simply errors out as "Couldn't start PanelPopout: Missing Selector"

**To Reproduce**
1. Install PanelPopout extension
2. Simply errors out when enabled, and does not work.

**Expected behavior**
It shouldn't error out and work as intended.

**Screenshots**
![Screenshot_20210818_132820](https://user-images.githubusercontent.com/64794941/129883011-f3459f59-dd1d-4671-ac4d-c4f6207c1efd.png)

**Details (please complete the following information):**
 - Addon Name: PanelPopout
 - Addon Version: 1.1.0
 - Discord Release Channel: Stable

**Additional context**
 - Operating System: Kubuntu Linux 20.04 (linux kernel 5.11)
 - Discord Version: 0.0.15

![Screenshot_20210818_133244](https://user-images.githubusercontent.com/64794941/129883599-0f52978e-cc37-4dd6-9a85-03ef8e367265.png)

**Comment by QbDesu** [comment]
there is 2 things that fail because of the latest discord update
1: it can't find the selector
2: popouts broke in ZeresPluginLibrary
I'm waiting for 2 to be fixed before fixing 1, without 2 being fixed it won't work anyway

**Comment by plasmaborg** [comment]
Oh, poputs are seems to work now. Issue 2 fixed!

**Comment by plasmaborg** [comment]
why did you discontinue panelpoput? it was great :(( (oh, we got userdetails that integrates it, thats cool)

**Comment by QbDesu** [comment]
Because a similar functionality is now part of UserDetails. The plugin hasn't worked in over a month now and it's near impossible to fix.
