### ISSUE TITLE
Plugin broken for the past 2 weeks

### ISSUE THREAD

**Issue by HarrieMcRacc** [QbDesu/BetterDiscordAddons#71]
It's probably likely that it's broken cause of the new discord update but I'm plopping this here regardless 
cause nobody else has done it yet.
![image](https://user-images.githubusercontent.com/73590885/195592231-489e621c-bc54-4081-923a-af8d473c216b.png)

**Comment by HarrieMcRacc** [comment]
Sorry, didn't realize the plugin isn't being maintained anymore, ggs

**Comment by QbDesu** [comment]
I recommend using EmoteReplacer instead. It has even more features and works with the latest version. You gotta download it from the author's Github repo though because the new version has not been verified on the official BD site yet.

**Comment by SeasonalFerret** [comment]
> It has even more features

Yeah, no.
FreeMoji lets you send multiple emojis within one [Enter] press by splitting messages up, with a customizable delay.
I've yet to see any other plugin do this.
