### ISSUE TITLE
DoubleClickVoiceChannels no longer works

### ISSUE THREAD

**Issue by Bamboozul** [QbDesu/BetterDiscordAddons#72]
After the latest Discord changes, the plugin no longer works.

**Comment by ronfino** [comment]
Yup...

**Comment by Moosyu** [comment]
Its discontinued

**Comment by Bamboozul** [comment]
> Its discontinued 

Do you know any working alternative for it?

**Comment by moosyu** [comment]
> > Its discontinued
> 
> Do you know any working alternative for it?

Sorry I'm actually stupid I thought this was Freemoji sorry. Many extensions are being updated after the discord changes so I reckon just wait until the developer fixes it.

**Comment by QbDesu** [comment]
Yeah I'm gonna try to fix it soon. Currently out cold with covid though.

**Comment by Bamboozul** [comment]
> Yeah I'm gonna try to fix it soon. Currently out cold with covid though.

Take good care of yourself, and I hope you recover quickly.

**Comment by moosyu** [comment]
> Yeah I'm gonna try to fix it soon. Currently out cold with covid though.

Sorry to hear about that, I hope you have a speedy recovery!

**Comment by GRMZR** [comment]
Hi, are there any updates regarding the fix?

**Comment by Bamboozul** [comment]
> Hi, are there any updates regarding the fix?

The plugin was updated today, and it's working as intended.
