### ISSUE TITLE
BetterBotTags doesn't work

### ISSUE THREAD

**Issue by rollingmoai** [QbDesu/BetterDiscordAddons#73]
**Describe the bug**
BetterBotTags loads but doesn't work at all

**To Reproduce**
1. Load BetterBotTags
2. Webhook tags are not replaced

**Expected behavior**
Webhooks tags should be replaced

**Screenshots**
![image](https://user-images.githubusercontent.com/75471378/199145546-75b938b0-7485-40a0-8ab1-9ca2f4c5f317.png)

**Details (please complete the following information):**
 - Addon Name: BetterBotTags
 - Addon Version: 1.1.0
 - Discord Release Channel: PTB

**Additional context**

**Comment by QbDesu** [comment]
I just pushed a fix, update when it asks you to

**Comment by rollingmoai** [comment]
Thanks
