### ISSUE TITLE
[BUG] Double Click Voice Channels Plugin

### ISSUE THREAD

**Issue by BlueStarBRS** [QbDesu/BetterDiscordAddons#74]
The plugin dosn´t work you click one time and you´re connected so the plugin dosnt work

pls fix thx.

i press only one time and youre in if you double clickm the profilepic preview opens in voice channel
![ezgif-1-1cff8d1c61](https://user-images.githubusercontent.com/25110093/200095381-9ee35fe0-9103-441c-880a-c388319a1929.gif)

**Comment by BlueStarBRS** [comment]
update the  plugin pls mate @QbDesu

**Comment by QbDesu** [comment]
The plugin was updated a few days ago and should be working now as soon as you update.

**Comment by BlueStarBRS** [comment]
> The plugin was updated a few days ago and should be working now as soon as you update.

thank you <3
