### ISSUE TITLE
BetterBotTags Failed to resolve BotTag module

### ISSUE THREAD

**Issue by sponnify** [QbDesu/BetterDiscordAddons#75]
**Describe the bug**

**To Reproduce**
Attempt to enable the plugin in BD settings

**Screenshots**
![image](https://user-images.githubusercontent.com/69046095/200183767-e51c32c2-fcb5-46be-bbfa-12f2d8255ccc.png)

**Details (please complete the following information):**
 - Addon Name: BetterBotTags
 - Addon Version: Latest
 - Discord Release Channel: Stable

**Comment by QbDesu** [comment]
I just pushed a fix, update when it asks you to
