### ISSUE TITLE
BetterBotTags: Space before the [Webhook] and [Bot] tag, looking like [ Webhook] and [ Bot] instead.

### ISSUE THREAD

**Issue by MysticMia** [QbDesu/BetterDiscordAddons#77]
**Describe the bug**
The blue [Bot] and [Webhook] tags have a little blue space to the left of them. A sort of spacebar or spacing.
This is likely caused by the disabled icon, because when the icon is enabled, this isn't an 'issue' anymore.

**To Reproduce**
1. Enable mod
2. Look at a bot or webhook
3. Observe

**Expected behavior**
Expected there to not be a spacebar :P

**Screenshots**
Mod enabled, icons enabled
![image](https://user-images.githubusercontent.com/65396931/216794163-74189d98-0e71-488f-abea-721fbf8dd849.png)
![image](https://user-images.githubusercontent.com/65396931/216794082-d570acf7-46c2-4e5e-a785-0026dd29099b.png)
Mod enabled, icons disabled
![image](https://user-images.githubusercontent.com/65396931/216794149-e3fbec22-18fb-4e11-8fcc-f11af1963f64.png)
![image](https://user-images.githubusercontent.com/65396931/216794098-2a095979-db90-4fc2-9161-a1205e94bdb2.png)

Mod disabled
![image](https://user-images.githubusercontent.com/65396931/216794134-70f06378-5419-4495-a6ad-b46421cbb10b.png)

**Details (please complete the following information):**
 - Addon Name: BetterBotTags
 - Addon Version: v2.0.0
 - Discord Release Channel: Stable

**Comment by QbDesu** [comment]
Thank you for reporting it. Fixed in version 2.0.1 along side some other minor things, update when it asks you to.
