### ISSUE TITLE
[Enhancement] Freemoji, Allow sending stickers as a URL like emojis.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [QbDesu/BetterDiscordAddons#8]
The title itself is quite self explanatory. Expand from just Emotes to Stickers as well, letting them be sent as a URL just like the emojis.

**Comment by QbDesu** [comment]
use https://github.com/discord-stickers/FreeCommunityStickers
I don't have plans to add it and the plugin was recently taken down from the official plugins site because of legal concerns, so I won't risk my plugin experiencing the same fate.
