### ISSUE TITLE
Emoji with text shows link

### ISSUE THREAD

**Issue by Kilowog01** [QbDesu/BetterDiscordAddons#9]
The title is self-explanatory and the image illustrates the problem well.
If the emoji is sent alone, the link disappears.
![emoji](https://user-images.githubusercontent.com/16064499/133495466-9dff3440-3a37-47c2-8010-ab08acfe83a7.png)

**Comment by QbDesu** [comment]
Yes, this is how discord's embeds work. There is nothing I can do about it.

From the description:
> it won't work mid-sentence or for sending multiple emoji at once. But for single emote messages it's almost much seemless, just the size is slightly different.
